name: CI for Practice

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Debug permissions
      run: |
        ls -la node_modules/.bin/
        chmod +x node_modules/.bin/jest
    
    - name: Run tests
      run: npm test 